### ISSUE TITLE
Dock becomes smaller

### ISSUE THREAD

**Issue by dalmatian1231** [rtrouton/profiles#1]
After deploy this Siri disable profile onto MBP on 10.12, Dock become much smaller and can't adjust Dock size in system preferences since it's locked.

**Comment by rtrouton** [comment]
Unable to reproduce issue. Testing done:

Install all Siri-related profiles in VM
Run through several iterations of resizing and repositioning Dock

I've posted a video of my testing here:
[https://www.youtube.com/watch?v=hHMnXBejpwU](https://www.youtube.com/watch?v=hHMnXBejpwU)
