### ISSUE TITLE
Successful Install?

### ISSUE THREAD

**Issue by strikeing789d** [rtrouton/profiles#10]
Hi,

I downloaded the config file and it installed successfully and worked on one computer. However on another computer it installed successfully but I can still open blacklisted apps no problem. What am I doing wrong? 

Both computers are running the same os version.

**Comment by rtrouton** [comment]
If it worked fine on the one computer but not on the second, that indicates an issue with the second computer.

**Comment by strikeing789d** [comment]
@rtrouton Thank you for the reply. What do you think it could be? If it says it was installed "successfully" what can cause something so simple as a blacklist to not work? The computers are all cloned from one another...and are identical minus Mac addresses and serial numbers. I just don't understand why it would not work and yes I restarted....several times.

**Comment by UpDev1010** [comment]
Hi
Would you kindly let me know how to install plist file in mac os?

Thanks.
