### ISSUE TITLE
Missing SkipAnalytics and SkipAssistance profiles

### ISSUE THREAD

**Issue by Niek** [rtrouton/profiles#11]
Any chance you can add these profiles? These are two annoying popup screens I get in Big Sur for new user accounts.

**Comment by tempora-mutantur** [comment]
Would like to use it as well

**Comment by tempora-mutantur** [comment]
@Niek 
Found out that Analytics can be skipped with this

https://github.com/rtrouton/profiles/blob/fdf87986f70fbebfd815d466050a6747cbe6fc6b/SetDiagnosticandUsageReportSettings/SetDiagnosticandUsageReportSettings.mobileconfig

**Comment by rtrouton** [comment]
No need to wait on me, this tool will help you build these profiles for your own use:

https://imazing.com/profile-editor

![Screen Shot 2022-02-22 at 8 33 29 AM](https://user-images.githubusercontent.com/618055/155142915-e43a7d09-b499-4684-97be-45c327cac455.png)
