### ISSUE TITLE
Feature request - Enable Sharing -> Remote Management

### ISSUE THREAD

**Issue by tsinghzf** [rtrouton/profiles#13]
Hi,

Is there a way how I can auto checkmark  System Prefs -> Sharing -> remote management where in option everything is checked except show when being observed or everything is checked as well?

**Comment by rtrouton** [comment]
Not with a profile. If you want this capability, file feedback with Apple:

https://feedbackassistant.apple.com/
https://developer.apple.com/bug-reporting/

For more information on configuration of Apple Remote Desktop, please see the links below:

https://macops.ca/managing-screen-sharing-in-monterey-12.1/
https://support.apple.com/HT209161
