### ISSUE TITLE
Feature requests - Macos12 Passwords in System Pref pane

### ISSUE THREAD

**Issue by tsinghzf** [rtrouton/profiles#14]
Is there a way either a config file or a script that can be pushed to remove or hide Passwords as an option in System Preferences?

**Comment by rtrouton** [comment]
I’m not understanding which specific functionality is being requested, in the context of removing or hiding passwords. Please provide additional information.

**Comment by tsinghzf** [comment]
in macos12, when you open up system preferences, they have a pane called Passwords. I am trying to find a way to hide it using Jamf so it is automated but haven't been able to. Is there a way that you know of that can be built?

**Comment by tsinghzf** [comment]
Link - https://www.macrumors.com/2021/06/11/macos-monterey-password-updates/ this is what I am referring to. We don't want users to save things and don't want it available as an option either. I have another ticket open with Jamf that their config doesn't work the way it should
