### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by quintendewilde** [rtrouton/profiles#2]
With this absurd change in maxosx I want to change this back to the original way of working?

How do I do this

**Comment by rtrouton** [comment]
Could you please be more specific about what you're trying to accomplish? The more details you can provide, the more I'll be able to assist.

**Comment by rtrouton** [comment]
No response in over two months = closing this issue.

**Comment by quintendewilde** [comment]
My apologies! This was about the ICloud harddrive or the not seeing to local harddrive anymore. Fixed!
