### ISSUE TITLE
skip data and privacy mobileconfig

### ISSUE THREAD

**Issue by n0brainer** [rtrouton/profiles#3]
I uploaded this to jamf pro 10.2.2, it will create the entry, but won't have any configurations
<img width="1268" alt="screen shot 2018-05-02 at 10 10 15 am" src="https://user-images.githubusercontent.com/2116991/39531573-0fba5ca6-4df1-11e8-9044-c5c73050c7bf.png">

**Comment by rtrouton** [comment]
That's a problem on Jamf's end, not a problem with the profile itself.
