### ISSUE TITLE
wifi icon hide code not working for 10.13 Help please and thank you 

### ISSUE THREAD

**Issue by Sensire1** [rtrouton/profiles#5]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.apple.mcxMenuExtras</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>Bluetooth.menu</key>
								<false/>
								<key>Displays.menu</key>
								<false/>
								<key>TimeMachine.menu</key>
								<false/>
								<key>delaySeconds</key>
								<real>1</real>
							</dict>
						</dict>
					</array>
					<key>mcx_targets</key>
					<array>
						<string>user</string>
					</array>
				</dict>
			</dict>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>MCXToProfile.ae5c4c7c-c354-453b-bd15-d37437b46d2c.alacarte.customsettings.36b14197-3388-492c-b7a1-cae748143969</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>36b14197-3388-492c-b7a1-cae748143969</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Included custom settings:
com.apple.mcxMenuExtras
</string>
	<key>PayloadDisplayName</key>
	<string>MenuExtra</string>
	<key>PayloadIdentifier</key>
	<string>org.sacredsf.profile.menuextra</string>
	<key>PayloadOrganization</key>
	<string></string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>ae5c4c7c-c354-453b-bd15-d37437b46d2c</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>PayloadContent</key>
			<dict>
				<key>com.apple.mcxMenuExtras</key>
				<dict>
					<key>Forced</key>
					<array>
						<dict>
							<key>mcx_preference_settings</key>
							<dict>
								<key>Bluetooth.menu</key>
								<false/>
								<key>Displays.menu</key>
								<false/>
								<key>TimeMachine.menu</key>
								<false/>
								<key>delaySeconds</key>
								<real>1</real>
							</dict>
						</dict>
					</array>
					<key>mcx_targets</key>
					<array>
						<string>user</string>
					</array>
				</dict>
			</dict>
			<key>PayloadEnabled</key>
			<true/>
			<key>PayloadIdentifier</key>
			<string>MCXToProfile.ae5c4c7c-c354-453b-bd15-d37437b46d2c.alacarte.customsettings.36b14197-3388-492c-b7a1-cae748143969</string>
			<key>PayloadType</key>
			<string>com.apple.ManagedClient.preferences</string>
			<key>PayloadUUID</key>
			<string>36b14197-3388-492c-b7a1-cae748143969</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Included custom settings:
com.apple.mcxMenuExtras
</string>
	<key>PayloadDisplayName</key>
	<string>MenuExtra</string>
	<key>PayloadIdentifier</key>
	<string>org.sacredsf.profile.menuextra</string>
	<key>PayloadOrganization</key>
	<string></string>
	<key>PayloadRemovalDisallowed</key>
	<true/>
	<key>PayloadScope</key>
	<string>System</string>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>ae5c4c7c-c354-453b-bd15-d37437b46d2c</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>

**Comment by Sensire1** [comment]
Please be aware I’m new to this . Ths is not my code I may have done this incorrectly also for the owner of this code my apologies . No credit taken on my part

**Comment by rtrouton** [comment]
I don't think this is from one of my profiles. Closing issue.
